# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='registry.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eregistry.proto\"0\n\rServerAddress\x12\x0c\n\x04port\x18\x01 \x01(\x05\x12\x11\n\taddresses\x18\x02 \x03(\t\"F\n\x12\x43lientRegistration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2I\n\x0cOaasRegistry\x12\x39\n\x10registerServcice\x12\x13.ClientRegistration\x1a\x0e.ServerAddress\"\x00\x62\x06proto3'
)




_SERVERADDRESS = _descriptor.Descriptor(
  name='ServerAddress',
  full_name='ServerAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='port', full_name='ServerAddress.port', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='addresses', full_name='ServerAddress.addresses', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=66,
)


_CLIENTREGISTRATION = _descriptor.Descriptor(
  name='ClientRegistration',
  full_name='ClientRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='ClientRegistration.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='ClientRegistration.namespace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='ClientRegistration.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['ServerAddress'] = _SERVERADDRESS
DESCRIPTOR.message_types_by_name['ClientRegistration'] = _CLIENTREGISTRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServerAddress = _reflection.GeneratedProtocolMessageType('ServerAddress', (_message.Message,), {
  'DESCRIPTOR' : _SERVERADDRESS,
  '__module__' : 'registry_pb2'
  # @@protoc_insertion_point(class_scope:ServerAddress)
  })
_sym_db.RegisterMessage(ServerAddress)

ClientRegistration = _reflection.GeneratedProtocolMessageType('ClientRegistration', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTREGISTRATION,
  '__module__' : 'registry_pb2'
  # @@protoc_insertion_point(class_scope:ClientRegistration)
  })
_sym_db.RegisterMessage(ClientRegistration)



_OAASREGISTRY = _descriptor.ServiceDescriptor(
  name='OaasRegistry',
  full_name='OaasRegistry',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=140,
  serialized_end=213,
  methods=[
  _descriptor.MethodDescriptor(
    name='registerServcice',
    full_name='OaasRegistry.registerServcice',
    index=0,
    containing_service=None,
    input_type=_CLIENTREGISTRATION,
    output_type=_SERVERADDRESS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OAASREGISTRY)

DESCRIPTOR.services_by_name['OaasRegistry'] = _OAASREGISTRY

# @@protoc_insertion_point(module_scope)
