# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import  oaas_grpc.rpc.registry_pb2 as registry__pb2


class OaasRegistryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.registerServcice = channel.unary_unary(
                '/OaasRegistry/registerServcice',
                request_serializer=registry__pb2.ClientRegistration.SerializeToString,
                response_deserializer=registry__pb2.ServerAddress.FromString,
                )


class OaasRegistryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registerServcice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OaasRegistryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registerServcice': grpc.unary_unary_rpc_method_handler(
                    servicer.registerServcice,
                    request_deserializer=registry__pb2.ClientRegistration.FromString,
                    response_serializer=registry__pb2.ServerAddress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OaasRegistry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OaasRegistry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registerServcice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OaasRegistry/registerServcice',
            registry__pb2.ClientRegistration.SerializeToString,
            registry__pb2.ServerAddress.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
