# @generated by generate_proto_mypy_stubs.py.  Do not edit!
import sys
from google.protobuf.descriptor import (
    Descriptor as google___protobuf___descriptor___Descriptor,
    FileDescriptor as google___protobuf___descriptor___FileDescriptor,
)

from google.protobuf.internal.containers import (
    RepeatedCompositeFieldContainer as google___protobuf___internal___containers___RepeatedCompositeFieldContainer,
)

from google.protobuf.message import (
    Message as google___protobuf___message___Message,
)

from typing import (
    Iterable as typing___Iterable,
    Optional as typing___Optional,
    Text as typing___Text,
)

from typing_extensions import (
    Literal as typing_extensions___Literal,
)

builtin___bool = bool
builtin___bytes = bytes
builtin___float = float
builtin___int = int

DESCRIPTOR: google___protobuf___descriptor___FileDescriptor = ...

class ServiceDefinition(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    name: typing___Text = ...
    namespace: typing___Text = ...
    version: typing___Text = ...
    protocol: typing___Text = ...
    def __init__(
        self,
        *,
        name: typing___Optional[typing___Text] = None,
        namespace: typing___Optional[typing___Text] = None,
        version: typing___Optional[typing___Text] = None,
        protocol: typing___Optional[typing___Text] = None,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "name",
            b"name",
            "namespace",
            b"namespace",
            "protocol",
            b"protocol",
            "version",
            b"version",
        ],
    ) -> None: ...

type___ServiceDefinition = ServiceDefinition

class ServiceIpLink(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    ip: typing___Text = ...
    port: builtin___int = ...
    def __init__(
        self,
        *,
        ip: typing___Optional[typing___Text] = None,
        port: typing___Optional[builtin___int] = None,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["ip", b"ip", "port", b"port"]
    ) -> None: ...

type___ServiceIpLink = ServiceIpLink

class ServiceAddress(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def locations(self) -> type___ServiceIpLink: ...
    def __init__(
        self,
        *,
        locations: typing___Optional[type___ServiceIpLink] = None,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions___Literal["locations", b"locations"]
    ) -> builtin___bool: ...
    def ClearField(
        self, field_name: typing_extensions___Literal["locations", b"locations"]
    ) -> None: ...

type___ServiceAddress = ServiceAddress

class ServiceRegistration(google___protobuf___message___Message):
    DESCRIPTOR: google___protobuf___descriptor___Descriptor = ...
    @property
    def serviceDefinition(self) -> type___ServiceDefinition: ...
    @property
    def serviceAddress(
        self,
    ) -> google___protobuf___internal___containers___RepeatedCompositeFieldContainer[
        type___ServiceAddress
    ]: ...
    def __init__(
        self,
        *,
        serviceDefinition: typing___Optional[type___ServiceDefinition] = None,
        serviceAddress: typing___Optional[
            typing___Iterable[type___ServiceAddress]
        ] = None,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions___Literal[
            "serviceDefinition", b"serviceDefinition"
        ],
    ) -> builtin___bool: ...
    def ClearField(
        self,
        field_name: typing_extensions___Literal[
            "serviceAddress",
            b"serviceAddress",
            "serviceDefinition",
            b"serviceDefinition",
        ],
    ) -> None: ...

type___ServiceRegistration = ServiceRegistration
