# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
    name="registry.proto",
    package="",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0eregistry.proto\x1a\x1bgoogle/protobuf/empty.proto"W\n\x11ServiceDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x10\n\x08protocol\x18\x04 \x01(\t")\n\rServiceIpLink\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05"3\n\x0eServiceAddress\x12!\n\tlocations\x18\x01 \x01(\x0b\x32\x0e.ServiceIpLink"m\n\x13ServiceRegistration\x12-\n\x11serviceDefinition\x18\x01 \x01(\x0b\x32\x12.ServiceDefinition\x12\'\n\x0eserviceAddress\x18\x02 \x03(\x0b\x32\x0f.ServiceAddress2\x8a\x01\n\x0cOaasRegistry\x12\x41\n\x0fregisterService\x12\x14.ServiceRegistration\x1a\x16.google.protobuf.Empty"\x00\x12\x37\n\x0eresolveService\x12\x12.ServiceDefinition\x1a\x0f.ServiceAddress"\x00\x62\x06proto3',
    dependencies=[
        google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
    ],
)


_SERVICEDEFINITION = _descriptor.Descriptor(
    name="ServiceDefinition",
    full_name="ServiceDefinition",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="name",
            full_name="ServiceDefinition.name",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="namespace",
            full_name="ServiceDefinition.namespace",
            index=1,
            number=2,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="version",
            full_name="ServiceDefinition.version",
            index=2,
            number=3,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="protocol",
            full_name="ServiceDefinition.protocol",
            index=3,
            number=4,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=47,
    serialized_end=134,
)


_SERVICEIPLINK = _descriptor.Descriptor(
    name="ServiceIpLink",
    full_name="ServiceIpLink",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="ip",
            full_name="ServiceIpLink.ip",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="port",
            full_name="ServiceIpLink.port",
            index=1,
            number=2,
            type=5,
            cpp_type=1,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=136,
    serialized_end=177,
)


_SERVICEADDRESS = _descriptor.Descriptor(
    name="ServiceAddress",
    full_name="ServiceAddress",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="locations",
            full_name="ServiceAddress.locations",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=179,
    serialized_end=230,
)


_SERVICEREGISTRATION = _descriptor.Descriptor(
    name="ServiceRegistration",
    full_name="ServiceRegistration",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="serviceDefinition",
            full_name="ServiceRegistration.serviceDefinition",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=1,
            has_default_value=False,
            default_value=None,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="serviceAddress",
            full_name="ServiceRegistration.serviceAddress",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=232,
    serialized_end=341,
)

_SERVICEADDRESS.fields_by_name["locations"].message_type = _SERVICEIPLINK
_SERVICEREGISTRATION.fields_by_name[
    "serviceDefinition"
].message_type = _SERVICEDEFINITION
_SERVICEREGISTRATION.fields_by_name["serviceAddress"].message_type = _SERVICEADDRESS
DESCRIPTOR.message_types_by_name["ServiceDefinition"] = _SERVICEDEFINITION
DESCRIPTOR.message_types_by_name["ServiceIpLink"] = _SERVICEIPLINK
DESCRIPTOR.message_types_by_name["ServiceAddress"] = _SERVICEADDRESS
DESCRIPTOR.message_types_by_name["ServiceRegistration"] = _SERVICEREGISTRATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ServiceDefinition = _reflection.GeneratedProtocolMessageType(
    "ServiceDefinition",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERVICEDEFINITION,
        "__module__": "registry_pb2"
        # @@protoc_insertion_point(class_scope:ServiceDefinition)
    },
)
_sym_db.RegisterMessage(ServiceDefinition)

ServiceIpLink = _reflection.GeneratedProtocolMessageType(
    "ServiceIpLink",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERVICEIPLINK,
        "__module__": "registry_pb2"
        # @@protoc_insertion_point(class_scope:ServiceIpLink)
    },
)
_sym_db.RegisterMessage(ServiceIpLink)

ServiceAddress = _reflection.GeneratedProtocolMessageType(
    "ServiceAddress",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERVICEADDRESS,
        "__module__": "registry_pb2"
        # @@protoc_insertion_point(class_scope:ServiceAddress)
    },
)
_sym_db.RegisterMessage(ServiceAddress)

ServiceRegistration = _reflection.GeneratedProtocolMessageType(
    "ServiceRegistration",
    (_message.Message,),
    {
        "DESCRIPTOR": _SERVICEREGISTRATION,
        "__module__": "registry_pb2"
        # @@protoc_insertion_point(class_scope:ServiceRegistration)
    },
)
_sym_db.RegisterMessage(ServiceRegistration)


_OAASREGISTRY = _descriptor.ServiceDescriptor(
    name="OaasRegistry",
    full_name="OaasRegistry",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=344,
    serialized_end=482,
    methods=[
        _descriptor.MethodDescriptor(
            name="registerService",
            full_name="OaasRegistry.registerService",
            index=0,
            containing_service=None,
            input_type=_SERVICEREGISTRATION,
            output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name="resolveService",
            full_name="OaasRegistry.resolveService",
            index=1,
            containing_service=None,
            input_type=_SERVICEDEFINITION,
            output_type=_SERVICEADDRESS,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_OAASREGISTRY)

DESCRIPTOR.services_by_name["OaasRegistry"] = _OAASREGISTRY

# @@protoc_insertion_point(module_scope)
